version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: agarmayfer-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: agarmayfer
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: agarmayfer-backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

volumes:
  mongo_data:
