# Netlify configuration for agarmayfer-pro-edition
# This file tells Netlify to use the root directory for the frontend
# and can be extended for backend functions if needed.
[build]
  publish = "."
  # If you have a build command (for React, Vue, etc.), set it here:
  # command = "npm run build"

# Uncomment below if you want to use Netlify Functions (serverless backend)
#[functions]
#  directory = "netlify/functions"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
